version: "3"
services:
  bytecom-sicoba:
    image: registry.gitlab.com/bytecom/sicoba:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 850M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - bytecom-net
networks:
  bytecom-net: