version: "3"
services:
  web:
    image: registry.gitlab.com/bytecom/sicoba:latest
    environment:
      PROFILE: "production"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PASS: "${DATABASE_PASS}"
      APP_TOKEN: "${APP_TOKEN}"
      DOMAIN: "${DOMAIN}"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: