version: "3"
services:
  web:
    image: clairtonluz/bytecom:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 850M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - bytecomnet
networks:
  bytecomnet: