version: "3"
services:
  web:
    image: registry.gitlab.com/bytecom/sicoba:latest
    environment:
#      PROFILE: "default"
      DATABASE_HOST: "${DATABASE_HOST}"
#      DATABASE_PASS: "${DATABASE_PASS}"
#      APP_TOKEN: "${APP_TOKEN}"
#      DOMAIN: "${DOMAIN}"
#      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "4000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: bytecom
#      POSTGRES_USER: bytecom
#      POSTGRES_DB: bytecom
#    networks:
#      - webnet

networks:
  webnet: