
spring:
  application:
    name: sicoba
  datasource:
    url: jdbc:postgresql://localhost:5432/bytecom?user=bytecom&password=bytecom
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 1
    initialSize: 1
    removeAbandoned: true
  jpa:
    show-sql: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  mail:
    default-encoding: UTF-8
    host: smtp.zoho.com
    username: sicoba@bytecominformatica.com.br
    password: secretPassword
    port: 465
    protocol: smtp
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.smtp.socketFactory.fallback: false
    properties.mail.smtp.startssl.enable: true
    properties.mail.smtp.socketFactory.port: 465
    properties.mail.smtp.debug: true
  sendgrid:
    api-key: your-secret-api-key
  jackson:
    time-zone: America/Fortaleza
myapp:
  email:
    sac: sac@bytecominformatica.com.br
    admin: admin@bytecominformatica.com.br
    suporte: suporte@bytecominformatica.com.br
  boleto:
    notification-url: https://mydomain.com.br/api/gerencianet/%d/notification

---
# DEFAULT
spring:
  profiles: default
myapp:
  token: tokenTeste
---
# STAGING
spring:
  profiles: staging

---
# PRODUCTION
spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
  jpa:
    show-sql: false
    properties:
       hibernate.format_sql: false