#PARA DESENVOLVIMENTO: jdbc:postgresql://localhost:5432/bytecom?user=bytecom&password=bytecom
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 1
    initialSize: 1
    removeAbandoned: true
#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: create-drop