CREATE TABLE nfe
(
  id         SERIAL                 NOT NULL PRIMARY KEY,
  cliente_id int not null references cliente(id),
  nome varchar(100) not null,
  logradouro varchar(100) not null,
  numero varchar(30) not null,
  complemento varchar(255),
  bairo varchar(100) not null,
  cidade varchar(100) not null,
  uf varchar(2) not null,
  cep varchar(9) not null,
  cnpj varchar(30),
  ie varchar(30),
  cpf varchar(30),
  rg varchar(30),
  dia_vencimento int not null,
  modelo int not null,
  cfop int not null default 0,
  telefone varchar(30) not null,
  email varchar(100),
  tipo_assinante varchar(100) not null,
  tipo_utilizacao varchar(100) not null,
  data_emissao date not null,
  data_prestacao date not null,
  observacao varchar(255),
  codigo_municipio varchar(255),
  created_at     TIMESTAMP    NOT NULL,
  updated_at     TIMESTAMP    NOT NULL,
  created_by     VARCHAR(255) NOT NULL,
  updated_by     VARCHAR(255) NOT NULL
);

CREATE TABLE nfe_item
(
  id         SERIAL                 NOT NULL PRIMARY KEY,
  classificacao_servico varchar(255) not null,
  descricao varchar(255) not null,
  valor_unitario decimal(12, 2) not null,
  icms decimal(12, 2) not null,
  aliquota_reducao decimal(12, 2) not null,
  unidade varchar(100) not null,
  quantidade_contratada decimal(12, 2) not null,
  quantidade_fornecida decimal(12, 2) not null,
  aliquota_icms decimal(12, 2) not null,
  bc decimal(12, 2) not null,
  valores_isentos decimal(12, 2) not null,
  outros_valores decimal(12, 2) not null,
  desconto decimal(12, 2) not null,
  valor_aproximado_tributos_federal decimal(12, 2) not null,
  valor_aproximado_tributos_estadual decimal(12, 2) not null,
  valor_aproximado_tributos_municipal decimal(12, 2) not null,
  charge_id int not null references charge(id) unique,
  nfe_id int not null references nfe(id),
  created_at     TIMESTAMP    NOT NULL,
  updated_at     TIMESTAMP    NOT NULL,
  created_by     VARCHAR(255) NOT NULL,
  updated_by     VARCHAR(255) NOT NULL
);


