package br.com.clairtonluz.sicoba.model.entity.financeiro.syncnfe;

public enum ClassificacaoServico {
    ASSINATURA_DE_SERVICOS_DE_TELEFONIA(101),
    ASSINATURA_DE_SERVICOS_DE_COMUNICACAO_DE_DADO(102),
    ASSINATURA_DE_SERVICOS_DE_TV_POR_ASSINATURA(103),
    ASSINATURA_DE_SERVICOS_DE_PROVIMENTO_DE_ACESSO_A_INTERNET(104),
    ASSINATURA_DE_SERVICOS_MULTIMIDIA(105),
    ASSINATURA_DE_OUTROS_SERVICOS(199),
    HABILITACAO_DE_SERVICOS_DE_TELEFONIA(201),
    HABILITACAO_DE_SERVICOS_DE_COMUNICACAO_DE_DADOS(202),
    HABILITACAO_DE_SERVICOS_DE_TV_POR_ASSINATURA(203),
    HABILITACAO_DE_SERVICOS_DE_PROVIMENTO_DE_ACESSO_A_INTERNET(204),
    HABILITACAO_DE_SERVICOS_MULTIMIDIA(205),
    HABILITACAO_DE_OUTROS_SERVICOS(299),
    SERVICO_MEDIDO_CHAMADAS_LOCAIS(301),
    SERVICO_MEDIDO_CHAMADAS_INTERURBANAS_NO_ESTADO(302),
    SERVICO_MEDIDO_CHAMADAS_INTERURBANAS_PARA_FORA_DO_ESTADO(303),
    SERVICO_MEDIDO_CHAMADAS_INTERNACIONAIS(304),
    SERVICO_MEDIDO_NUMEROS_ESPECIAIS_0300_0500_0800_ETC(305),
    SERVICO_MEDIDO_COMUNICACAO_DE_DADO(306),
    SERVICO_MEDIDO_CHAMADAS_ORIGINADAS_EM_ROAMING(307),
    SERVICO_MEDIDO_CHAMADAS_RECEBIDAS_EM_ROAMING(308),
    SERVICO_MEDIDO_ADICIONAL_DE_CHAMADA(309),
    SERVICO_MEDIDO_PROVIMENTO_DE_ACESSO_A_INTERNET(310),
    SERVICO_MEDIDO_PAY_PER_VIEW_PROGRAMACAO_TV(311),
    SERVICO_MEDIDO_MENSAGEM_SMS(312),
    SERVICO_MEDIDO_MENSAGEM_MMS(313),
    SERVICO_MEDIDO_OUTRAS_MENSAGENS(314),
    SERVICO_MEDIDO_SERVICOS_MULTIMIDIA(315),
    SERVICO_MEDIDO_OUTROS_SERVICOS(399),
    SERVICO_MEDIDO_OUTROS_SERVICOS_401(401),
    CARTAO_TELEFONICO_TELEFONIA_MOVEL(402),
    CARTAO_DE_PROVIMENTO_DE_ACESSO_A_INTERNET(403),
    FICHA_TELEFONICA405_RECARGA_DE_CREDITOS_TELEFONE_FIXA(404),
    RECARGA_DE_CREDITOS_TELEFONE_MOVEL(406),
    RECARGA_DE_CREDITOS_PROVIMENTO_DE_ACESSO_A_INTERNET(407),
    OUTRAS_COBRANCAS_DE_ASSINANTES_DE_PLANO_SERVICO_PRE_PAGO(499),
    SERVICO_ADICIONAL_SUBSTITUICAO_DE_NUMERO_OU_TROCA_DE_APARELHO_OU_EMISSAO_DE_2A_VIA_DE_CONTA_OU_CONTA_DETALHADA_ETC(501),
    SERVICO_FACILIDADES_IDENTIFICADOR_DE_CHAMADAS_OU_CAIXA_POSTAL_OU_TRANSFERÊNCIA_TEMPORARIA_OU_NAO_PERTURBE_ETC(502),
    OUTROS_SERVICOS(599),
    ENERGIA_ELETRICA_CONSUMO(601),
    ENERGIA_ELETRICA_DEMANDA(602),
    ENERGIA_ELETRICA_SERVICOS_VISTORIA_DE_UNIDADE_CONSUMIDORA_OU_AFERICAO_DE_MEDIDOR_OU_LIGACAO_OU_RELIGACAO_OU_TROCA_DE_MEDIDOR_ETC(603),
    ENERGIA_ELETRICA_ENCARGOS_EMERGENCIAIS(604),
    ENERGIA_ELETRICA_OUTROS(699),
    LOCACAO_DE_APARELHO_TELEFONICO(701),
    LOCACAO_DE_APARELHO_IDENTIFICADOR_DE_CHAMADAS(702),
    LOCACAO_DE_MODEM(703),
    LOCACAO_DE_RACK(704),
    LOCACAO_DE_SALA_OU_RECINTO(705),
    LOCACAO_DE_ROTEADOR(706),
    LOCACAO_DE_SERVIDOR(707),
    LOCACAO_DE_MULTIPLEXADOR(708),
    LOCACAO_DE_DECODIFICADOR_OU_CONVERSOR(709),
    OUTRAS_LOCACOES(799),
    COBRANCA_DE_SERVICOS_DE_TERCEIROS(801),
    COBRANCA_DE_SEGUROS(802),
    COBRANCA_DE_FINANCIAMENTO_DE_APARELHO_OU_SERVICOS(803),
    COBRANCA_DE_JUROS_DE_MORA_POR_ATRASO_DE_PAGAMENTO(804),
    COBRANCA_DE_MULTA_DE_MORA_POR_ATRASO_DE_PAGAMENTO(805),
    COBRANCA_DE_CONTA_DE_MESES_ANTERIORES(806),
    OUTRAS_COBRANCAS(899),
    CREDITO_RELATIVO_A_IMPUGNACAO_DE_SERVICOS(901),
    CREDITO_REFERENTE_AJUSTE_DE_CONTA(902),
    REDUTOR_ENERGIA_ELETRICA_IN_NO_306_2003_PIS_OU_COFINS_OU_IRPJ_OU_CSLL(903),
    OUTROS_CREDITOS(999);

    private final int codigo;

    ClassificacaoServico(int codigo) {
        this.codigo = codigo;
    }

    public int getCodigo() {
        return codigo;
    }
}
